import Navbar from "@/components/navbar/Navbar";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/utils/provider/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          <ReactQueryProvider>
            <Navbar />
            {children}
            {/* <Footer /> */}
          </ReactQueryProvider>
        </div>
      </body>
    </html>
  );
}
